export interface SeedData {
  medicines: any[];
  pharmacies: any[];
  medicineInventory: any[];
  hospitals: any[];
  bloodBanks: any[];
  bloodInventory: any[];
  transplantCenters: any[];
  organAvailability: any[];
  referrals: any[];
  iotDevices: any[];
  users: any[];
}

export const sampleDistricts = [
  'Coimbatore',
  'Chennai',
  'Madurai',
  'Salem',
  'Tiruchirappalli',
  'Erode',
  'Tiruppur',
  'Namakkal',
  'Karur',
  'Dindigul',
  'Nilgiris',
  'Thanjavur',
  'Vellore',
  'Tirunelveli',
  'Cuddalore'
];

export const seedMedicines = [
  {
    id: 'med-01',
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol / Acetaminophen',
    category: 'Analgesic & Antipyretic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: false,
    description: 'Relieves mild to moderate pain and reduces fever.',
    uses: ['Fever', 'Headache', 'Body pain', 'Post-vaccine fever']
  },
  {
    id: 'med-02',
    name: 'Paracetamol 650mg (Dolo)',
    genericName: 'Paracetamol',
    category: 'Analgesic & Antipyretic',
    dosageForm: 'Tablet',
    strength: '650mg',
    manufacturer: 'Micro Labs',
    prescriptionRequired: false,
    description: 'High-strength fever reducer and analgesic for severe body aches.',
    uses: ['High fever', 'Viral fever', 'Joint pain']
  },
  {
    id: 'med-03',
    name: 'Amoxicillin 500mg (Mox 500)',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic (Penicillin)',
    dosageForm: 'Capsule',
    strength: '500mg',
    manufacturer: 'Sun Pharma',
    prescriptionRequired: true,
    description: 'Broad-spectrum antibiotic for bacterial respiratory and ear/throat infections.',
    uses: ['Throat infection', 'Pneumonia', 'Dental abscess', 'Ear infection']
  },
  {
    id: 'med-04',
    name: 'Azithromycin 500mg (Azithral)',
    genericName: 'Azithromycin',
    category: 'Antibiotic (Macrolide)',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Alembic Pharmaceuticals',
    prescriptionRequired: true,
    description: 'Used to treat various bacterial infections of lungs, skin, and ENT.',
    uses: ['Chest infection', 'Sinusitis', 'Tonsillitis', 'Skin infection']
  },
  {
    id: 'med-05',
    name: 'Oral Rehydration Salts (ORS W.H.O.)',
    genericName: 'Sodium Chloride, Potassium Chloride, Sodium Citrate, Dextrose',
    category: 'Electrolyte Replenisher',
    dosageForm: 'Sachet Powder',
    strength: '21.8g / 1 Litre',
    manufacturer: 'FDC Ltd (Electral)',
    prescriptionRequired: false,
    description: 'Essential life-saving hydration for acute diarrhea, vomiting, and heat exhaustion.',
    uses: ['Diarrhea', 'Dehydration', 'Heat stroke', 'Vomiting']
  },
  {
    id: 'med-06',
    name: 'Metformin 500mg (Glycomet)',
    genericName: 'Metformin Hydrochloride',
    category: 'Anti-Diabetic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'USV Ltd',
    prescriptionRequired: true,
    description: 'First-line medication for the treatment of type 2 diabetes.',
    uses: ['Type 2 Diabetes', 'Blood sugar control']
  },
  {
    id: 'med-07',
    name: 'Glimepiride 2mg (Amaryl)',
    genericName: 'Glimepiride',
    category: 'Anti-Diabetic',
    dosageForm: 'Tablet',
    strength: '2mg',
    manufacturer: 'Sanofi India',
    prescriptionRequired: true,
    description: 'Sulfonylurea that stimulates pancreas to release insulin.',
    uses: ['Type 2 Diabetes']
  },
  {
    id: 'med-08',
    name: 'Human Insulin Regular (Actrapid)',
    genericName: 'Regular Human Insulin',
    category: 'Insulin / Hormone',
    dosageForm: 'Vial Injection',
    strength: '40 IU/ml (10ml)',
    manufacturer: 'Novo Nordisk',
    prescriptionRequired: true,
    description: 'Short-acting insulin for urgent blood sugar regulation.',
    uses: ['Type 1 Diabetes', 'Type 2 Diabetes', 'Diabetic ketoacidosis']
  },
  {
    id: 'med-09',
    name: 'Amlodipine 5mg (Amlong)',
    genericName: 'Amlodipine Besylate',
    category: 'Anti-Hypertensive',
    dosageForm: 'Tablet',
    strength: '5mg',
    manufacturer: 'Micro Labs',
    prescriptionRequired: true,
    description: 'Calcium channel blocker to lower high blood pressure and prevent angina.',
    uses: ['High Blood Pressure', 'Angina (Chest pain)', 'Heart health']
  },
  {
    id: 'med-10',
    name: 'Telmisartan 40mg (Telma 40)',
    genericName: 'Telmisartan',
    category: 'Anti-Hypertensive',
    dosageForm: 'Tablet',
    strength: '40mg',
    manufacturer: 'Glenmark Pharmaceuticals',
    prescriptionRequired: true,
    description: 'Angiotensin II receptor blocker for hypertension and cardiovascular risk reduction.',
    uses: ['Hypertension', 'Kidney protection in diabetics']
  },
  {
    id: 'med-11',
    name: 'Atorvastatin 10mg (Atorva)',
    genericName: 'Atorvastatin',
    category: 'Lipid-Lowering (Statin)',
    dosageForm: 'Tablet',
    strength: '10mg',
    manufacturer: 'Zydus Cadila',
    prescriptionRequired: true,
    description: 'Lowers bad cholesterol (LDL) and triglycerides, reduces heart attack risk.',
    uses: ['High Cholesterol', 'Heart attack prevention']
  },
  {
    id: 'med-12',
    name: 'Pantoprazole 40mg (Pan 40)',
    genericName: 'Pantoprazole Sodium',
    category: 'Proton Pump Inhibitor (Antacid)',
    dosageForm: 'Tablet',
    strength: '40mg',
    manufacturer: 'Alkem Laboratories',
    prescriptionRequired: false,
    description: 'Reduces stomach acid, treats acid reflux, GERD, and peptic ulcers.',
    uses: ['Gastritis', 'Acidity', 'Heartburn', 'Stomach ulcer']
  },
  {
    id: 'med-13',
    name: 'Cetirizine 10mg (Cetzine)',
    genericName: 'Cetirizine Dihydrochloride',
    category: 'Anti-Allergic (Antihistamine)',
    dosageForm: 'Tablet',
    strength: '10mg',
    manufacturer: 'Dr. Reddy Laboratories',
    prescriptionRequired: false,
    description: 'Relieves allergy symptoms like runny nose, sneezing, itching, and hives.',
    uses: ['Allergic rhinitis', 'Sneezing', 'Skin allergy', 'Insect bites']
  },
  {
    id: 'med-14',
    name: 'Montelukast + Levocetirizine (Montair LC)',
    genericName: 'Montelukast 10mg + Levocetirizine 5mg',
    category: 'Respiratory Anti-Allergic',
    dosageForm: 'Tablet',
    strength: '10mg / 5mg',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Dual-action allergy and asthma symptom control.',
    uses: ['Allergic asthma', 'Severe seasonal allergies', 'Chronic cough']
  },
  {
    id: 'med-15',
    name: 'Salbutamol Inhaler (Asthalin 100mcg)',
    genericName: 'Salbutamol / Albuterol',
    category: 'Bronchodilator',
    dosageForm: 'Inhaler / MDI',
    strength: '100mcg (200 doses)',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Emergency fast-acting rescue inhaler for asthma attacks and wheezing.',
    uses: ['Asthma attack', 'COPD', 'Bronchospasm', 'Shortness of breath']
  },
  {
    id: 'med-16',
    name: 'Budesonide Respules 0.5mg (Budecort)',
    genericName: 'Budesonide',
    category: 'Inhaled Corticosteroid',
    dosageForm: 'Nebulizer Solution',
    strength: '0.5mg / 2ml',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Anti-inflammatory nebulizer liquid for respiratory distress in children and adults.',
    uses: ['Severe asthma', 'Croup', 'Acute wheezing']
  },
  {
    id: 'med-17',
    name: 'Ciprofloxacin 500mg (Ciplox)',
    genericName: 'Ciprofloxacin',
    category: 'Fluoroquinolone Antibiotic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Effective against urinary tract infections, severe diarrhea, and typhoid.',
    uses: ['UTI', 'Typhoid fever', 'Gastroenteritis', 'Bone infection']
  },
  {
    id: 'med-18',
    name: 'Doxycycline 100mg (Doxicip)',
    genericName: 'Doxycycline Hyclate',
    category: 'Tetracycline Antibiotic',
    dosageForm: 'Capsule',
    strength: '100mg',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Used for rural tick-borne fevers, scrub typhus, leptospirosis, and malaria prophylaxis.',
    uses: ['Scrub typhus', 'Leptospirosis', 'Acne', 'Respiratory infection']
  },
  {
    id: 'med-19',
    name: 'Snake Antivenom Serum (Polyvalent)',
    genericName: 'Anti-Snake Venom Polyvalent (Cobra, Krait, Russell Viper, Saw-Scaled Viper)',
    category: 'Emergency Antidote / Biological',
    dosageForm: 'Vial Lyophilized Injection',
    strength: '10ml (Neutralizes 4 venoms)',
    manufacturer: 'Bharat Serums & Vaccines',
    prescriptionRequired: true,
    description: 'Critical life-saving emergency injection for venomous snake bites in rural areas.',
    uses: ['Snake bite envenomation', 'Rural emergency antidote']
  },
  {
    id: 'med-20',
    name: 'Anti-Rabies Vaccine (Rabipur / Vaxirab)',
    genericName: 'Purified Chick Embryo Cell Rabies Vaccine',
    category: 'Vaccine / Biological',
    dosageForm: 'Intramuscular Injection',
    strength: '2.5 IU / dose',
    manufacturer: 'Zydus Cadila / Chiron',
    prescriptionRequired: true,
    description: 'Emergency post-exposure prophylaxis for animal / dog bites.',
    uses: ['Dog bite', 'Monkey bite', 'Rabies prevention']
  },
  {
    id: 'med-21',
    name: 'Tetanus Toxoid Vaccine (TT 0.5ml)',
    genericName: 'Tetanus Toxoid Adsorbed',
    category: 'Vaccine',
    dosageForm: 'Ampoule Injection',
    strength: '0.5ml (5 LF)',
    manufacturer: 'Serum Institute of India',
    prescriptionRequired: false,
    description: 'Immediate prevention of tetanus following rust injuries, road accidents, or farm cuts.',
    uses: ['Rust injury', 'Wound trauma', 'Maternity tetanus immunization']
  },
  {
    id: 'med-22',
    name: 'Ibuprofen + Paracetamol (Combiflam)',
    genericName: 'Ibuprofen 400mg + Paracetamol 325mg',
    category: 'NSAID / Painkiller',
    dosageForm: 'Tablet',
    strength: '400mg / 325mg',
    manufacturer: 'Sanofi India',
    prescriptionRequired: false,
    description: 'Combination anti-inflammatory and pain relief for muscle aches and toothache.',
    uses: ['Toothache', 'Muscle sprain', 'Joint swelling', 'Menstrual pain']
  },
  {
    id: 'med-23',
    name: 'Diclofenac Sodium Gel 1% (Volini)',
    genericName: 'Diclofenac Diethylamine Gel',
    category: 'Topical Analgesic',
    dosageForm: 'Gel Ointment',
    strength: '30g Tube',
    manufacturer: 'Sun Pharma',
    prescriptionRequired: false,
    description: 'Fast pain relief gel for back pain, knee pain, sprains, and sports injuries.',
    uses: ['Backache', 'Sprain', 'Knee osteoarthritis', 'Neck stiffness']
  },
  {
    id: 'med-24',
    name: 'Povidone Iodine Ointment 5% (Betadine)',
    genericName: 'Povidone-Iodine 5% w/w',
    category: 'Antiseptic & Disinfectant',
    dosageForm: 'Topical Ointment',
    strength: '20g Tube',
    manufacturer: 'Win-Medicare',
    prescriptionRequired: false,
    description: 'Antiseptic ointment for cuts, scrapes, minor burns, and wound dressing.',
    uses: ['Wound dressing', 'Burns', 'Minor cuts', 'Infection prevention']
  },
  {
    id: 'med-25',
    name: 'Silver Sulfadiazine Cream 1% (Silverex)',
    genericName: 'Silver Sulfadiazine',
    category: 'Burn Therapy Cream',
    dosageForm: 'Topical Cream',
    strength: '25g Tube',
    manufacturer: 'Ranbaxy / Sun Pharma',
    prescriptionRequired: false,
    description: 'Antibacterial cream preventing and treating infection in second/third-degree burns.',
    uses: ['Burn wounds', 'Skin graft areas', 'Scalds']
  },
  {
    id: 'med-26',
    name: 'Ondansetron 4mg (Emeset)',
    genericName: 'Ondansetron Hydrochloride',
    category: 'Antiemetic',
    dosageForm: 'Tablet',
    strength: '4mg',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'Prevents nausea and vomiting caused by viral gastroenteritis or chemotherapy.',
    uses: ['Vomiting', 'Nausea', 'Post-operative vomiting']
  },
  {
    id: 'med-27',
    name: 'Domperidone 10mg (Domstal)',
    genericName: 'Domperidone',
    category: 'Prokinetic / Antiemetic',
    dosageForm: 'Tablet',
    strength: '10mg',
    manufacturer: 'Torrent Pharmaceuticals',
    prescriptionRequired: false,
    description: 'Relieves fullness, nausea, and promotes gastrointestinal motility.',
    uses: ['Indigestion', 'Bloating', 'Nausea']
  },
  {
    id: 'med-28',
    name: 'Ceftriaxone 1g Injection (Monocef)',
    genericName: 'Ceftriaxone Sodium',
    category: '3rd Gen Cephalosporin Antibiotic',
    dosageForm: 'IV/IM Vial',
    strength: '1g Powder with Water',
    manufacturer: 'Aristo Pharmaceuticals',
    prescriptionRequired: true,
    description: 'Potent injectable antibiotic for severe hospital infections, meningitis, and sepsis.',
    uses: ['Meningitis', 'Sepsis', 'Severe typhoid', 'Pneumonia']
  },
  {
    id: 'med-29',
    name: 'Piperacillin + Tazobactam 4.5g (Pipzo)',
    genericName: 'Piperacillin 4g + Tazobactam 0.5g',
    category: 'Broad Spectrum Antibiotic',
    dosageForm: 'IV Vial Injection',
    strength: '4.5g',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: true,
    description: 'ICU-grade antibiotic for critical hospital-acquired bacterial infections.',
    uses: ['ICU sepsis', 'Intra-abdominal infection', 'Severe pneumonia']
  },
  {
    id: 'med-30',
    name: 'Iron + Folic Acid (Autrin / Orofer XT)',
    genericName: 'Ferrous Ascorbate 100mg + Folic Acid 1.5mg',
    category: 'Hematinic / Blood Builder',
    dosageForm: 'Tablet',
    strength: '100mg / 1.5mg',
    manufacturer: 'Emcure Pharmaceuticals',
    prescriptionRequired: false,
    description: 'Essential iron supplement for anemia, pregnancy, and rural maternal nutrition.',
    uses: ['Iron deficiency anemia', 'Pregnancy support', 'General fatigue']
  },
  {
    id: 'med-31',
    name: 'Calcium Carbonate + Vitamin D3 (Shelcal 500)',
    genericName: 'Elemental Calcium 500mg + Vit D3 250 IU',
    category: 'Mineral & Vitamin',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Torrent Pharmaceuticals',
    prescriptionRequired: false,
    description: 'Maintains bone mineral density, treats osteoporosis and hypocalcemia.',
    uses: ['Bone health', 'Joint weakness', 'Post-menopause bone support']
  },
  {
    id: 'med-32',
    name: 'Vitamin C + Zinc (Limcee / Celin)',
    genericName: 'Ascorbic Acid 500mg + Zinc Sulphate',
    category: 'Immunity Supplement',
    dosageForm: 'Chewable Tablet',
    strength: '500mg',
    manufacturer: 'Abbott Healthcare',
    prescriptionRequired: false,
    description: 'Boosts immune defenses and accelerates wound healing.',
    uses: ['Immunity', 'Cold prevention', 'Skin healing']
  },
  {
    id: 'med-33',
    name: 'Methylcobalamin 1500mcg (Neurobion Forte)',
    genericName: 'Vitamin B12 + B Complex',
    category: 'Neuro-Vitamin',
    dosageForm: 'Tablet',
    strength: '1500mcg',
    manufacturer: 'Procter & Gamble Health',
    prescriptionRequired: false,
    description: 'Nerve regeneration supplement for diabetic neuropathy, numbness, and tingling.',
    uses: ['Nerve pain', 'Diabetic neuropathy', 'Tingling in feet']
  },
  {
    id: 'med-34',
    name: 'Tranexamic Acid 500mg (Texakind)',
    genericName: 'Tranexamic Acid',
    category: 'Anti-Fibrinolytic (Hemostatic)',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Mankind Pharma',
    prescriptionRequired: true,
    description: 'Controls excessive bleeding during heavy menstruation, trauma, or surgery.',
    uses: ['Severe bleeding', 'Post-partum hemorrhage', 'Dental bleeding']
  },
  {
    id: 'med-35',
    name: 'Levothyroxine 50mcg (Thyronorm)',
    genericName: 'Thyroxine Sodium',
    category: 'Thyroid Hormone',
    dosageForm: 'Tablet',
    strength: '50mcg',
    manufacturer: 'Abbott Healthcare',
    prescriptionRequired: true,
    description: 'Replaces deficient thyroid hormone in hypothyroidism.',
    uses: ['Hypothyroidism', 'Goiter', 'Thyroid deficiency']
  },
  {
    id: 'med-36',
    name: 'Levetiracetam 500mg (Levipil)',
    genericName: 'Levetiracetam',
    category: 'Anti-Epileptic / Anti-Convulsant',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Sun Pharma',
    prescriptionRequired: true,
    description: 'Prevents and controls seizures and epilepsy in pediatric and adult patients.',
    uses: ['Epilepsy', 'Fits / Seizures prevention']
  },
  {
    id: 'med-37',
    name: 'Sodium Valproate 300mg (Encorate)',
    genericName: 'Sodium Valproate Chrono',
    category: 'Anti-Epileptic',
    dosageForm: 'CR Tablet',
    strength: '300mg',
    manufacturer: 'Sun Pharma',
    prescriptionRequired: true,
    description: 'Mood stabilizer and broad-spectrum anti-convulsant for seizure disorders.',
    uses: ['Seizures', 'Bipolar disorder', 'Migraine prevention']
  },
  {
    id: 'med-38',
    name: 'Moxifloxacin Eye Drops 0.5% (Vigamox)',
    genericName: 'Moxifloxacin Ophthalmic Solution',
    category: 'Ophthalmic Antibiotic',
    dosageForm: 'Eye Drops',
    strength: '5ml Bottle',
    manufacturer: 'Alcon / Novartis',
    prescriptionRequired: true,
    description: 'Treats bacterial conjunctivitis (red eye), corneal ulcers, and eye infections.',
    uses: ['Conjunctivitis (Madras Eye)', 'Eye infection', 'Post-cataract surgery']
  },
  {
    id: 'med-39',
    name: 'Ciplox Otic Ear Drops (Ciprofloxacin 0.3%)',
    genericName: 'Ciprofloxacin Otic Solution',
    category: 'Otic Antibiotic',
    dosageForm: 'Ear Drops',
    strength: '10ml Bottle',
    manufacturer: 'Cipla Ltd',
    prescriptionRequired: false,
    description: 'Relieves middle ear pain, discharge, and bacterial otitis externa.',
    uses: ['Ear infection', 'Ear discharge', 'Swimmer ear']
  },
  {
    id: 'med-40',
    name: 'Normal Saline IV 0.9% (NS 500ml)',
    genericName: 'Sodium Chloride 0.9% w/v',
    category: 'Intravenous Fluid',
    dosageForm: 'IV Infusion Bottle',
    strength: '500ml',
    manufacturer: 'Baxter / Fresenius Kabi',
    prescriptionRequired: true,
    description: 'Standard isotonic fluid replacement for hypovolemia, trauma, and dehydration.',
    uses: ['Fluid resuscitation', 'Dehydration', 'IV medicine dilution']
  },
  {
    id: 'med-41',
    name: 'Ringer Lactate IV Infusion (RL 500ml)',
    genericName: 'Compound Sodium Lactate Solution',
    category: 'Intravenous Fluid',
    dosageForm: 'IV Infusion Bottle',
    strength: '500ml',
    manufacturer: 'Otsuka / Baxter',
    prescriptionRequired: true,
    description: 'Balanced crystalloid for trauma patients, severe blood loss, and surgical hydration.',
    uses: ['Trauma shock', 'Burns fluid resuscitation', 'Surgical hydration']
  },
  {
    id: 'med-42',
    name: 'Dextrose 5% IV Infusion (D5W 500ml)',
    genericName: 'Dextrose Anhydrous 5% w/v',
    category: 'Intravenous Fluid',
    dosageForm: 'IV Infusion Bottle',
    strength: '500ml',
    manufacturer: 'Fresenius Kabi',
    prescriptionRequired: true,
    description: 'Provides free water and carbohydrate calories in hypoglycemia and ketosis.',
    uses: ['Hypoglycemia', 'Post-operative fluid maintenance']
  },
  {
    id: 'med-43',
    name: 'Enoxaparin Sodium 40mg (Clexane)',
    genericName: 'Enoxaparin Low Molecular Weight Heparin',
    category: 'Anticoagulant (Blood Thinner)',
    dosageForm: 'Pre-filled Syringe Injection',
    strength: '0.4ml (40mg / 4000 IU)',
    manufacturer: 'Sanofi India',
    prescriptionRequired: true,
    description: 'Prevents blood clots in deep veins (DVT) and pulmonary embolism.',
    uses: ['Deep Vein Thrombosis', 'ICU blood clot prophylaxis', 'Dialysis']
  },
  {
    id: 'med-44',
    name: 'Deriphyllin Retard 150mg',
    genericName: 'Theophylline 115mg + Etofylline 35mg',
    category: 'Bronchodilator',
    dosageForm: 'Tablet',
    strength: '150mg',
    manufacturer: 'Zydus Cadila',
    prescriptionRequired: true,
    description: 'Sustained release tablet preventing chronic wheezing and nocturnal asthma.',
    uses: ['Chronic asthma', 'Bronchitis', 'Night-time cough']
  },
  {
    id: 'med-45',
    name: 'Metronidazole 400mg (Flagyl)',
    genericName: 'Metronidazole',
    category: 'Antiprotozoal & Antibacterial',
    dosageForm: 'Tablet',
    strength: '400mg',
    manufacturer: 'Abbott India',
    prescriptionRequired: true,
    description: 'Treats amoebic dysentery, dental infections, and anaerobic bacterial conditions.',
    uses: ['Amoebic diarrhea', 'Dysentery', 'Dental infection']
  },
  {
    id: 'med-46',
    name: 'Albendazole 400mg (Zentel)',
    genericName: 'Albendazole',
    category: 'Anthelmintic (Deworming)',
    dosageForm: 'Chewable Tablet',
    strength: '400mg',
    manufacturer: 'GlaxoSmithKline (GSK)',
    prescriptionRequired: false,
    description: 'Single-dose rural deworming tablet for roundworms, tapeworms, and hookworms.',
    uses: ['Intestinal worms', 'Rural school deworming program']
  },
  {
    id: 'med-47',
    name: 'Clopidogrel 75mg (Clopilet)',
    genericName: 'Clopidogrel Bisulphate',
    category: 'Antiplatelet',
    dosageForm: 'Tablet',
    strength: '75mg',
    manufacturer: 'Sun Pharma',
    prescriptionRequired: true,
    description: 'Prevents platelet clumping in patients after stent insertion or heart attack.',
    uses: ['Heart attack prevention', 'Stroke prevention', 'Post-angioplasty']
  },
  {
    id: 'med-48',
    name: 'Furosemide 40mg (Lasix)',
    genericName: 'Furosemide',
    category: 'Loop Diuretic (Water Pill)',
    dosageForm: 'Tablet',
    strength: '40mg',
    manufacturer: 'Sanofi India',
    prescriptionRequired: true,
    description: 'Removes excess fluid buildup in congestive heart failure and kidney disease.',
    uses: ['Edema (Fluid swelling)', 'Heart failure', 'High BP emergency']
  },
  {
    id: 'med-49',
    name: 'Hydrocortisone Sodium Succinate 100mg (Primacort)',
    genericName: 'Hydrocortisone',
    category: 'Corticosteroid Injection',
    dosageForm: 'IV Vial Injection',
    strength: '100mg',
    manufacturer: 'Macleods Pharma',
    prescriptionRequired: true,
    description: 'Emergency anti-inflammatory and immunosuppressant for anaphylaxis and severe asthma.',
    uses: ['Anaphylactic shock', 'Severe allergic reaction', 'Septic shock']
  },
  {
    id: 'med-50',
    name: 'Adrenaline Injection 1:1000 (Epinephrine)',
    genericName: 'Adrenaline / Epinephrine',
    category: 'Emergency Resuscitation / Vasopressor',
    dosageForm: '1ml Ampoule',
    strength: '1mg / 1ml',
    manufacturer: 'Neon Laboratories',
    prescriptionRequired: true,
    description: 'Life-saving resuscitation medication for cardiac arrest and severe anaphylaxis.',
    uses: ['Cardiac arrest', 'Severe anaphylaxis shock', 'Severe croup']
  },
  {
    id: 'med-51',
    name: 'Atropine Sulphate Injection (0.6mg/ml)',
    genericName: 'Atropine Sulphate',
    category: 'Anticholinergic / Antidote',
    dosageForm: 'Ampoule Injection',
    strength: '0.6mg / 1ml',
    manufacturer: 'Troikaa Pharmaceuticals',
    prescriptionRequired: true,
    description: 'Emergency antidote for organophosphorus (pesticide) poisoning and bradycardia in farm workers.',
    uses: ['Pesticide poisoning antidote', 'Severe low heart rate (Bradycardia)']
  }
];

export const seedPharmacies = [
  {
    id: 'ph-01',
    name: 'Sri Lakshmi Medicals & 24x7 Emergency Drugs',
    ownerName: 'M. Shanmugam',
    licenseNumber: 'TN-ERD-2023-8891',
    address: '42, Bhavani Main Road, Near Bus Stand, Erode',
    district: 'Erode',
    lat: 11.3410,
    lng: 77.7172,
    phone: '+91 94432 11029',
    is24x7: true,
    rating: 4.8,
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString()
  },
  {
    id: 'ph-02',
    name: 'Kovai Jan Aushadhi Kendra (Govt Generic Medicine)',
    ownerName: 'K. Rajendran',
    licenseNumber: 'TN-CBE-2022-4412',
    address: '108, Gandhipuram 7th Street, Coimbatore',
    district: 'Coimbatore',
    lat: 11.0168,
    lng: 76.9558,
    phone: '+91 98421 77340',
    is24x7: false,
    rating: 4.9,
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString()
  },
  {
    id: 'ph-03',
    name: 'Annai Medical Store & Rural Health Depot',
    ownerName: 'S. Parvathi',
    licenseNumber: 'TN-MDU-2021-9921',
    address: '15, Melur Main Road, Othakadai, Madurai',
    district: 'Madurai',
    lat: 9.9252,
    lng: 78.1198,
    phone: '+91 94440 22918',
    is24x7: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString()
  },
  {
    id: 'ph-04',
    name: 'Salem Star Pharmacy & Cold Chain Center',
    ownerName: 'V. Sundaram',
    licenseNumber: 'TN-SLM-2023-1120',
    address: '88, Cherry Road, Hasthampatti, Salem',
    district: 'Salem',
    lat: 11.6643,
    lng: 78.1460,
    phone: '+91 97890 33411',
    is24x7: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString()
  },
  {
    id: 'ph-05',
    name: 'Trichy Apollo Pharmacy & Rural Delivery Unit',
    ownerName: 'Dr. C. Balaji',
    licenseNumber: 'TN-TRY-2022-7729',
    address: '22, Thillai Nagar 11th Cross, Tiruchirappalli',
    district: 'Tiruchirappalli',
    lat: 10.7905,
    lng: 78.7047,
    phone: '+91 94431 88902',
    is24x7: true,
    rating: 4.8,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString()
  },
  {
    id: 'ph-06',
    name: 'Tiruppur Textile City Medicals',
    ownerName: 'P. Murugan',
    licenseNumber: 'TN-TPR-2023-5561',
    address: '67, Avinashi Road, Near Old Bus Stand, Tiruppur',
    district: 'Tiruppur',
    lat: 11.1085,
    lng: 77.3411,
    phone: '+91 98430 44190',
    is24x7: false,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString()
  },
  {
    id: 'ph-07',
    name: 'Namakkal Poultry Belt Pharmacy & Vet Drugs',
    ownerName: 'N. Senthil Kumar',
    licenseNumber: 'TN-NMK-2022-3341',
    address: '14, Mohanur Road, Namakkal',
    district: 'Namakkal',
    lat: 11.2189,
    lng: 78.1674,
    phone: '+91 94422 66019',
    is24x7: false,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString()
  },
  {
    id: 'ph-08',
    name: 'Karur Cauvery Medical Agencies',
    ownerName: 'A. Dhanasekaran',
    licenseNumber: 'TN-KRR-2021-4490',
    address: '53, Kovai Road, Karur',
    district: 'Karur',
    lat: 10.9601,
    lng: 78.0766,
    phone: '+91 98424 55901',
    is24x7: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 18 * 60000).toISOString()
  },
  {
    id: 'ph-09',
    name: 'Dindigul Rock Fort Medical Store',
    ownerName: 'G. Kannan',
    licenseNumber: 'TN-DGL-2023-2219',
    address: '9, Main Bazaar, Near Clock Tower, Dindigul',
    district: 'Dindigul',
    lat: 10.3673,
    lng: 77.9803,
    phone: '+91 97870 11822',
    is24x7: false,
    rating: 4.4,
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString()
  },
  {
    id: 'ph-10',
    name: 'Ooty Nilgiris Hill Station Pharmacy',
    ownerName: 'J. Thangavel',
    licenseNumber: 'TN-NLG-2022-7711',
    address: '12, Commercial Road, Charing Cross, Ooty',
    district: 'Nilgiris',
    lat: 11.4102,
    lng: 76.6950,
    phone: '+91 94860 33119',
    is24x7: true,
    rating: 4.9,
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString()
  },
  {
    id: 'ph-11',
    name: 'Thanjavur Delta Medical Care',
    ownerName: 'R. Veeramani',
    licenseNumber: 'TN-TNJ-2023-6621',
    address: '34, Medical College Road, Thanjavur',
    district: 'Thanjavur',
    lat: 10.7870,
    lng: 79.1378,
    phone: '+91 94433 77810',
    is24x7: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 6 * 60000).toISOString()
  },
  {
    id: 'ph-12',
    name: 'Vellore CMC Junction Medicals',
    ownerName: 'E. Sivakumar',
    licenseNumber: 'TN-VEL-2022-1192',
    address: '101, Ida Scudder Road, Vellore',
    district: 'Vellore',
    lat: 12.9165,
    lng: 79.1325,
    phone: '+91 98410 99823',
    is24x7: true,
    rating: 4.9,
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString()
  },
  {
    id: 'ph-13',
    name: 'Chennai Central 24x7 Life Meds',
    ownerName: 'S. Natarajan',
    licenseNumber: 'TN-CHN-2023-0091',
    address: '8, Poonamallee High Road, Park Town, Chennai',
    district: 'Chennai',
    lat: 13.0827,
    lng: 80.2707,
    phone: '+91 98400 12345',
    is24x7: true,
    rating: 4.8,
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString()
  },
  {
    id: 'ph-14',
    name: 'Tirunelveli Nellai Pharma Care',
    ownerName: 'K. Meenakshi',
    licenseNumber: 'TN-TNV-2022-5519',
    address: '45, High Ground Road, Palayamkottai, Tirunelveli',
    district: 'Tirunelveli',
    lat: 8.7139,
    lng: 77.7567,
    phone: '+91 94421 88390',
    is24x7: false,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString()
  },
  {
    id: 'ph-15',
    name: 'Pollachi Coconut City Pharmacy',
    ownerName: 'V. Arumugam',
    licenseNumber: 'TN-CBE-2023-6612',
    address: '18, Palakkad Road, Pollachi',
    district: 'Coimbatore',
    lat: 10.6583,
    lng: 77.0089,
    phone: '+91 97899 44102',
    is24x7: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 9 * 60000).toISOString()
  },
  {
    id: 'ph-16',
    name: 'Mettupalayam Foot Hills Medicals',
    ownerName: 'M. Anand',
    licenseNumber: 'TN-CBE-2022-7819',
    address: '29, Annur Road, Mettupalayam',
    district: 'Coimbatore',
    lat: 11.2980,
    lng: 76.9450,
    phone: '+91 94437 22091',
    is24x7: false,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 45 * 60000).toISOString()
  },
  {
    id: 'ph-17',
    name: 'Gobichettipalayam Green Valley Meds',
    ownerName: 'T. Krishnan',
    licenseNumber: 'TN-ERD-2021-9934',
    address: '11, Sathyamangalam Main Road, Gobichettipalayam',
    district: 'Erode',
    lat: 11.4550,
    lng: 77.4330,
    phone: '+91 98427 11980',
    is24x7: true,
    rating: 4.8,
    updatedAt: new Date(Date.now() - 11 * 60000).toISOString()
  },
  {
    id: 'ph-18',
    name: 'Perundurai Highway Medical Hub',
    ownerName: 'D. Karthik',
    licenseNumber: 'TN-ERD-2023-3382',
    address: '89, National Highway 544, Near Tollgate, Perundurai',
    district: 'Erode',
    lat: 11.2760,
    lng: 77.5850,
    phone: '+91 94441 55902',
    is24x7: true,
    rating: 4.9,
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString()
  },
  {
    id: 'ph-19',
    name: 'Attur Rural Health Pharmacy',
    ownerName: 'B. Selvam',
    licenseNumber: 'TN-SLM-2022-8819',
    address: '76, Cuddalore Main Road, Attur',
    district: 'Salem',
    lat: 11.5970,
    lng: 78.6010,
    phone: '+91 97860 33499',
    is24x7: false,
    rating: 4.4,
    updatedAt: new Date(Date.now() - 22 * 60000).toISOString()
  },
  {
    id: 'ph-20',
    name: 'Cuddalore Coastal Pharma Center',
    ownerName: 'L. Jayaraman',
    licenseNumber: 'TN-CDL-2023-4410',
    address: '23, Imperial Road, Cuddalore Old Town',
    district: 'Cuddalore',
    lat: 11.7480,
    lng: 79.7714,
    phone: '+91 94432 99011',
    is24x7: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 14 * 60000).toISOString()
  }
];

export const seedHospitals = [
  {
    id: 'hosp-01',
    name: 'Government District Headquarters Hospital (GH)',
    type: 'GOVERNMENT',
    address: 'Brough Road, Near Railway Station, Erode',
    district: 'Erode',
    lat: 11.3425,
    lng: 77.7274,
    phone: '0424-2253301',
    emergencyPhone: '108 / 0424-2253300',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    beds: [
      { id: 'bed-01-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 250, availableBeds: 48, occupiedBeds: 202, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-01-2', category: 'ICU', categoryLabel: 'Intensive Care Unit (ICU)', totalBeds: 35, availableBeds: 6, occupiedBeds: 29, ventilatorCount: 20, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-01-3', category: 'EMERGENCY', categoryLabel: 'Emergency / Casualty', totalBeds: 20, availableBeds: 5, occupiedBeds: 15, ventilatorCount: 8, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-01-4', category: 'PEDIATRIC', categoryLabel: 'Pediatric (NICU/PICU)', totalBeds: 40, availableBeds: 12, occupiedBeds: 28, ventilatorCount: 6, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-01-5', category: 'MATERNITY', categoryLabel: 'Maternity Ward', totalBeds: 60, availableBeds: 14, occupiedBeds: 46, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-01-6', category: 'OXYGEN_SUPPORTED', categoryLabel: 'Oxygen Supported Beds', totalBeds: 80, availableBeds: 22, occupiedBeds: 58, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-02',
    name: 'Coimbatore Medical College Hospital (CMCH)',
    type: 'GOVERNMENT',
    address: 'Trichy Road, Sungam, Coimbatore',
    district: 'Coimbatore',
    lat: 11.0016,
    lng: 76.9665,
    phone: '0422-2301393',
    emergencyPhone: '108 / 0422-2300000',
    ambulanceAvailable: true,
    rating: 4.8,
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    beds: [
      { id: 'bed-02-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 800, availableBeds: 112, occupiedBeds: 688, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-02-2', category: 'ICU', categoryLabel: 'Trauma & Medical ICU', totalBeds: 90, availableBeds: 14, occupiedBeds: 76, ventilatorCount: 55, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-02-3', category: 'EMERGENCY', categoryLabel: 'Emergency Trauma Ward', totalBeds: 50, availableBeds: 9, occupiedBeds: 41, ventilatorCount: 20, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-02-4', category: 'PEDIATRIC', categoryLabel: 'Neonatal & Child ICU', totalBeds: 70, availableBeds: 18, occupiedBeds: 52, ventilatorCount: 15, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-02-5', category: 'MATERNITY', categoryLabel: 'Labor & Maternity', totalBeds: 120, availableBeds: 25, occupiedBeds: 95, ventilatorCount: 2, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-02-6', category: 'OXYGEN_SUPPORTED', categoryLabel: 'High Flow Oxygen Ward', totalBeds: 180, availableBeds: 45, occupiedBeds: 135, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-03',
    name: 'Government Rajaji Hospital (GRH Madurai)',
    type: 'GOVERNMENT',
    address: 'Panagal Road, Shenoy Nagar, Madurai',
    district: 'Madurai',
    lat: 9.9283,
    lng: 78.1322,
    phone: '0452-2532535',
    emergencyPhone: '108 / 0452-2532536',
    ambulanceAvailable: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    beds: [
      { id: 'bed-03-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 750, availableBeds: 95, occupiedBeds: 655, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-03-2', category: 'ICU', categoryLabel: 'Surgical & Cardiac ICU', totalBeds: 80, availableBeds: 11, occupiedBeds: 69, ventilatorCount: 40, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-03-3', category: 'EMERGENCY', categoryLabel: 'Casualty Trauma Care', totalBeds: 45, availableBeds: 7, occupiedBeds: 38, ventilatorCount: 18, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-03-4', category: 'PEDIATRIC', categoryLabel: 'Pediatric ICU', totalBeds: 60, availableBeds: 15, occupiedBeds: 45, ventilatorCount: 12, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-03-5', category: 'MATERNITY', categoryLabel: 'Maternity Unit', totalBeds: 100, availableBeds: 21, occupiedBeds: 79, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-03-6', category: 'OXYGEN_SUPPORTED', categoryLabel: 'Central Oxygen Line Beds', totalBeds: 150, availableBeds: 36, occupiedBeds: 114, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-04',
    name: 'Government Mohan Kumaramangalam Medical College Hospital',
    type: 'GOVERNMENT',
    address: 'Fort Main Road, Salem',
    district: 'Salem',
    lat: 11.6580,
    lng: 78.1510,
    phone: '0427-2211222',
    emergencyPhone: '108 / 0427-2211223',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    beds: [
      { id: 'bed-04-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 500, availableBeds: 78, occupiedBeds: 422, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-04-2', category: 'ICU', categoryLabel: 'ICU & CCU', totalBeds: 50, availableBeds: 8, occupiedBeds: 42, ventilatorCount: 25, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-04-3', category: 'EMERGENCY', categoryLabel: 'Emergency Ward', totalBeds: 30, availableBeds: 6, occupiedBeds: 24, ventilatorCount: 10, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-04-4', category: 'OXYGEN_SUPPORTED', categoryLabel: 'Oxygen Beds', totalBeds: 100, availableBeds: 28, occupiedBeds: 72, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-05',
    name: 'Mahatma Gandhi Memorial Government Hospital (MGMGH Trichy)',
    type: 'GOVERNMENT',
    address: 'Collector Office Road, Tiruchirappalli',
    district: 'Tiruchirappalli',
    lat: 10.8060,
    lng: 78.6920,
    phone: '0431-2412525',
    emergencyPhone: '108 / 0431-2412526',
    ambulanceAvailable: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
    beds: [
      { id: 'bed-05-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 600, availableBeds: 84, occupiedBeds: 516, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-05-2', category: 'ICU', categoryLabel: 'Multidisciplinary ICU', totalBeds: 60, availableBeds: 9, occupiedBeds: 51, ventilatorCount: 30, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-05-3', category: 'EMERGENCY', categoryLabel: 'Trauma & Emergency', totalBeds: 35, availableBeds: 5, occupiedBeds: 30, ventilatorCount: 12, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-05-4', category: 'PEDIATRIC', categoryLabel: 'Pediatric Care', totalBeds: 50, availableBeds: 11, occupiedBeds: 39, ventilatorCount: 8, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-06',
    name: 'Government Headquarters Hospital Tiruppur',
    type: 'GOVERNMENT',
    address: 'Kumaran Road, Near Railway Station, Tiruppur',
    district: 'Tiruppur',
    lat: 11.1090,
    lng: 77.3460,
    phone: '0421-2242333',
    emergencyPhone: '108 / 0421-2242334',
    ambulanceAvailable: true,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    beds: [
      { id: 'bed-06-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 350, availableBeds: 52, occupiedBeds: 298, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-06-2', category: 'ICU', categoryLabel: 'Intensive Care Unit', totalBeds: 30, availableBeds: 4, occupiedBeds: 26, ventilatorCount: 15, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-06-3', category: 'EMERGENCY', categoryLabel: 'Emergency Unit', totalBeds: 25, availableBeds: 4, occupiedBeds: 21, ventilatorCount: 6, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-07',
    name: 'Government District Hospital Namakkal',
    type: 'GOVERNMENT',
    address: 'Thuraiyur Road, Namakkal',
    district: 'Namakkal',
    lat: 11.2201,
    lng: 78.1710,
    phone: '04286-220450',
    emergencyPhone: '108 / 04286-220451',
    ambulanceAvailable: true,
    rating: 4.4,
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    beds: [
      { id: 'bed-07-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 220, availableBeds: 38, occupiedBeds: 182, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-07-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 20, availableBeds: 3, occupiedBeds: 17, ventilatorCount: 8, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-07-3', category: 'EMERGENCY', categoryLabel: 'Casualty', totalBeds: 15, availableBeds: 3, occupiedBeds: 12, ventilatorCount: 4, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-08',
    name: 'Government Medical College Hospital Karur',
    type: 'GOVERNMENT',
    address: 'K. Chettipalayam, Sanapiratti, Karur',
    district: 'Karur',
    lat: 10.9550,
    lng: 78.0810,
    phone: '04324-222333',
    emergencyPhone: '108 / 04324-222334',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 7 * 60000).toISOString(),
    beds: [
      { id: 'bed-08-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 400, availableBeds: 62, occupiedBeds: 338, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-08-2', category: 'ICU', categoryLabel: 'Critical Care ICU', totalBeds: 40, availableBeds: 5, occupiedBeds: 35, ventilatorCount: 18, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-08-3', category: 'EMERGENCY', categoryLabel: 'Emergency & Trauma', totalBeds: 25, availableBeds: 4, occupiedBeds: 21, ventilatorCount: 8, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-09',
    name: 'Government Headquarters Hospital Dindigul',
    type: 'GOVERNMENT',
    address: 'Trichy Road, Near Head Post Office, Dindigul',
    district: 'Dindigul',
    lat: 10.3620,
    lng: 77.9740,
    phone: '0451-2423333',
    emergencyPhone: '108 / 0451-2423334',
    ambulanceAvailable: true,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    beds: [
      { id: 'bed-09-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 280, availableBeds: 44, occupiedBeds: 236, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-09-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 25, availableBeds: 4, occupiedBeds: 21, ventilatorCount: 10, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-09-3', category: 'EMERGENCY', categoryLabel: 'Emergency Ward', totalBeds: 20, availableBeds: 3, occupiedBeds: 17, ventilatorCount: 5, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-10',
    name: 'Government District Hospital Ooty (Nilgiris)',
    type: 'GOVERNMENT',
    address: 'Hospital Road, Fernhill, Ooty',
    district: 'Nilgiris',
    lat: 11.4080,
    lng: 76.6990,
    phone: '0423-2442211',
    emergencyPhone: '108 / 0423-2442212',
    ambulanceAvailable: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 9 * 60000).toISOString(),
    beds: [
      { id: 'bed-10-1', category: 'GENERAL', categoryLabel: 'General Mountain Ward', totalBeds: 180, availableBeds: 32, occupiedBeds: 148, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-10-2', category: 'ICU', categoryLabel: 'High Altitude ICU', totalBeds: 18, availableBeds: 3, occupiedBeds: 15, ventilatorCount: 6, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-10-3', category: 'OXYGEN_SUPPORTED', categoryLabel: 'Oxygen Enriched Beds', totalBeds: 45, availableBeds: 12, occupiedBeds: 33, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-11',
    name: 'PSG Institute of Medical Sciences & Research (Private Charity)',
    type: 'PRIVATE',
    address: 'Avinashi Road, Peelamedu, Coimbatore',
    district: 'Coimbatore',
    lat: 11.0280,
    lng: 77.0040,
    phone: '0422-2570170',
    emergencyPhone: '0422-2598822 / 108',
    ambulanceAvailable: true,
    rating: 4.9,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    beds: [
      { id: 'bed-11-1', category: 'GENERAL', categoryLabel: 'Subsidized Ward', totalBeds: 300, availableBeds: 42, occupiedBeds: 258, ventilatorCount: 0, pricePerDay: 500, updatedAt: new Date().toISOString() },
      { id: 'bed-11-2', category: 'ICU', categoryLabel: 'Cardiac & Neuro ICU', totalBeds: 50, availableBeds: 7, occupiedBeds: 43, ventilatorCount: 30, pricePerDay: 2500, updatedAt: new Date().toISOString() },
      { id: 'bed-11-3', category: 'EMERGENCY', categoryLabel: '24x7 Emergency Resuscitation', totalBeds: 30, availableBeds: 6, occupiedBeds: 24, ventilatorCount: 15, pricePerDay: 1200, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-12',
    name: 'Christian Medical College (CMC Vellore)',
    type: 'PRIVATE',
    address: 'Ida Scudder Road, Vellore',
    district: 'Vellore',
    lat: 12.9246,
    lng: 79.1350,
    phone: '0416-2281000',
    emergencyPhone: '0416-2282222 / 108',
    ambulanceAvailable: true,
    rating: 4.95,
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString(),
    beds: [
      { id: 'bed-12-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 1200, availableBeds: 140, occupiedBeds: 1060, ventilatorCount: 0, pricePerDay: 600, updatedAt: new Date().toISOString() },
      { id: 'bed-12-2', category: 'ICU', categoryLabel: 'Multi-Organ Transplant ICU', totalBeds: 120, availableBeds: 15, occupiedBeds: 105, ventilatorCount: 80, pricePerDay: 3500, updatedAt: new Date().toISOString() },
      { id: 'bed-12-3', category: 'EMERGENCY', categoryLabel: 'Emergency Trauma Center', totalBeds: 60, availableBeds: 11, occupiedBeds: 49, ventilatorCount: 25, pricePerDay: 1500, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-13',
    name: 'Thanjavur Medical College Hospital',
    type: 'GOVERNMENT',
    address: 'Medical College Road, Thanjavur',
    district: 'Thanjavur',
    lat: 10.7850,
    lng: 79.1360,
    phone: '04362-240024',
    emergencyPhone: '108 / 04362-240025',
    ambulanceAvailable: true,
    rating: 4.7,
    updatedAt: new Date(Date.now() - 6 * 60000).toISOString(),
    beds: [
      { id: 'bed-13-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 550, availableBeds: 72, occupiedBeds: 478, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-13-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 50, availableBeds: 6, occupiedBeds: 44, ventilatorCount: 20, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-13-3', category: 'EMERGENCY', categoryLabel: 'Emergency Ward', totalBeds: 30, availableBeds: 4, occupiedBeds: 26, ventilatorCount: 8, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-14',
    name: 'Rajiv Gandhi Government General Hospital (RGGGH Chennai)',
    type: 'GOVERNMENT',
    address: 'EVR Periyar Salai, Park Town, Chennai',
    district: 'Chennai',
    lat: 13.0805,
    lng: 80.2785,
    phone: '044-25305000',
    emergencyPhone: '108 / 044-25305108',
    ambulanceAvailable: true,
    rating: 4.85,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    beds: [
      { id: 'bed-14-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 1500, availableBeds: 185, occupiedBeds: 1315, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-14-2', category: 'ICU', categoryLabel: 'Comprehensive ICU Complex', totalBeds: 160, availableBeds: 22, occupiedBeds: 138, ventilatorCount: 95, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-14-3', category: 'EMERGENCY', categoryLabel: 'State Trauma Center', totalBeds: 80, availableBeds: 14, occupiedBeds: 66, ventilatorCount: 35, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-15',
    name: 'Tirunelveli Medical College Hospital (TVMCH)',
    type: 'GOVERNMENT',
    address: 'High Ground, Palayamkottai, Tirunelveli',
    district: 'Tirunelveli',
    lat: 8.7180,
    lng: 77.7520,
    phone: '0462-2572733',
    emergencyPhone: '108 / 0462-2572734',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 11 * 60000).toISOString(),
    beds: [
      { id: 'bed-15-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 500, availableBeds: 65, occupiedBeds: 435, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-15-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 45, availableBeds: 6, occupiedBeds: 39, ventilatorCount: 20, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-16',
    name: 'Primary Health Center (PHC) Modakkurichi',
    type: 'PRIMARY_HEALTH_CENTER',
    address: 'Erode-Karur Road, Modakkurichi, Erode District',
    district: 'Erode',
    lat: 11.2330,
    lng: 77.7880,
    phone: '0424-2500110',
    emergencyPhone: '108',
    ambulanceAvailable: true,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    beds: [
      { id: 'bed-16-1', category: 'GENERAL', categoryLabel: 'Observation Beds', totalBeds: 12, availableBeds: 5, occupiedBeds: 7, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-16-2', category: 'MATERNITY', categoryLabel: 'Rural Delivery Room', totalBeds: 8, availableBeds: 3, occupiedBeds: 5, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-17',
    name: 'Community Health Center (CHC) Sathyamangalam',
    type: 'COMMUNITY_HEALTH_CENTER',
    address: 'Mysore Trunk Road, Sathyamangalam, Erode',
    district: 'Erode',
    lat: 11.5030,
    lng: 77.2400,
    phone: '04295-220330',
    emergencyPhone: '108 / 04295-220331',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    beds: [
      { id: 'bed-17-1', category: 'GENERAL', categoryLabel: 'Rural Ward', totalBeds: 30, availableBeds: 9, occupiedBeds: 21, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-17-2', category: 'EMERGENCY', categoryLabel: 'First Aid Emergency Bed', totalBeds: 6, availableBeds: 2, occupiedBeds: 4, ventilatorCount: 1, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-18',
    name: 'Government Hospital Pollachi',
    type: 'GOVERNMENT',
    address: 'Udumalai Road, Pollachi',
    district: 'Coimbatore',
    lat: 10.6600,
    lng: 77.0120,
    phone: '04259-224400',
    emergencyPhone: '108 / 04259-224401',
    ambulanceAvailable: true,
    rating: 4.6,
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    beds: [
      { id: 'bed-18-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 200, availableBeds: 35, occupiedBeds: 165, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-18-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 15, availableBeds: 3, occupiedBeds: 12, ventilatorCount: 6, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-19',
    name: 'Government Taluk Hospital Mettupalayam',
    type: 'GOVERNMENT',
    address: 'Kotagiri Road, Mettupalayam',
    district: 'Coimbatore',
    lat: 11.3010,
    lng: 76.9400,
    phone: '04254-222300',
    emergencyPhone: '108',
    ambulanceAvailable: true,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 14 * 60000).toISOString(),
    beds: [
      { id: 'bed-19-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 150, availableBeds: 28, occupiedBeds: 122, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-19-2', category: 'EMERGENCY', categoryLabel: 'Emergency Bed', totalBeds: 10, availableBeds: 2, occupiedBeds: 8, ventilatorCount: 2, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'hosp-20',
    name: 'Government Headquarters Hospital Cuddalore',
    type: 'GOVERNMENT',
    address: 'Sub-Jail Road, Cuddalore',
    district: 'Cuddalore',
    lat: 11.7500,
    lng: 79.7680,
    phone: '04142-230400',
    emergencyPhone: '108 / 04142-230401',
    ambulanceAvailable: true,
    rating: 4.5,
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    beds: [
      { id: 'bed-20-1', category: 'GENERAL', categoryLabel: 'General Ward', totalBeds: 300, availableBeds: 45, occupiedBeds: 255, ventilatorCount: 0, pricePerDay: 0, updatedAt: new Date().toISOString() },
      { id: 'bed-20-2', category: 'ICU', categoryLabel: 'ICU', totalBeds: 25, availableBeds: 4, occupiedBeds: 21, ventilatorCount: 10, pricePerDay: 0, updatedAt: new Date().toISOString() }
    ]
  }
];

export const seedBloodBanks = [
  {
    id: 'bb-01',
    name: 'Government District Blood Bank Erode',
    hospitalName: 'Government District Headquarters Hospital (GH Erode)',
    address: 'Brough Road, Erode',
    district: 'Erode',
    phone: '0424-2253305',
    emergencyContact: '+91 94432 99100',
    lat: 11.3425,
    lng: 77.7274,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-02',
    name: 'Coimbatore Medical College Central Blood Bank',
    hospitalName: 'Coimbatore Medical College Hospital (CMCH)',
    address: 'Sungam, Trichy Road, Coimbatore',
    district: 'Coimbatore',
    phone: '0422-2301399',
    emergencyContact: '+91 98421 88200',
    lat: 11.0016,
    lng: 76.9665,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-03',
    name: 'Madurai Rajaji Model Blood Bank & Component Separation Unit',
    hospitalName: 'Government Rajaji Hospital (GRH Madurai)',
    address: 'Panagal Road, Madurai',
    district: 'Madurai',
    phone: '0452-2532540',
    emergencyContact: '+91 94440 33100',
    lat: 9.9283,
    lng: 78.1322,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-04',
    name: 'Salem Government Hospital Regional Blood Center',
    hospitalName: 'GMKMC Hospital Salem',
    address: 'Fort Main Road, Salem',
    district: 'Salem',
    phone: '0427-2211228',
    emergencyContact: '+91 97890 55200',
    lat: 11.6580,
    lng: 78.1510,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-05',
    name: 'Trichy MGMGH Red Cross Blood Bank',
    hospitalName: 'Mahatma Gandhi Memorial Government Hospital',
    address: 'Collector Office Road, Tiruchirappalli',
    district: 'Tiruchirappalli',
    phone: '0431-2412530',
    emergencyContact: '+91 94431 77300',
    lat: 10.8060,
    lng: 78.6920,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-06',
    name: 'Tiruppur Rotary Central Blood Bank',
    hospitalName: 'GH Tiruppur',
    address: 'Kumaran Road, Tiruppur',
    district: 'Tiruppur',
    phone: '0421-2242340',
    emergencyContact: '+91 98430 66200',
    lat: 11.1090,
    lng: 77.3460,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-07',
    name: 'Vellore CMC Blood Transfusion Service',
    hospitalName: 'Christian Medical College Vellore',
    address: 'Ida Scudder Road, Vellore',
    district: 'Vellore',
    phone: '0416-2282050',
    emergencyContact: '+91 98410 77100',
    lat: 12.9246,
    lng: 79.1350,
    is24x7: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'bb-08',
    name: 'Chennai RGGGH State Apex Blood Bank',
    hospitalName: 'Rajiv Gandhi Government General Hospital Chennai',
    address: 'EVR Periyar Salai, Park Town, Chennai',
    district: 'Chennai',
    phone: '044-25305500',
    emergencyContact: '+91 98400 99100',
    lat: 13.0805,
    lng: 80.2785,
    is24x7: true,
    updatedAt: new Date().toISOString()
  }
];

export const seedTransplantCenters = [
  {
    id: 'tc-01',
    name: 'Government Rajaji Hospital Multi-Organ Transplant Center',
    hospitalId: 'hosp-03',
    address: 'Panagal Road, Madurai',
    district: 'Madurai',
    phone: '0452-2532535',
    coordinatorName: 'Dr. S. K. Murugesan (Zonal TRANSTAN Coordinator)',
    coordinatorPhone: '+91 94440 88210',
    accreditationNumber: 'TRANSTAN-TN-MDU-04',
    lat: 9.9283,
    lng: 78.1322,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'tc-02',
    name: 'Coimbatore Medical College Hospital Organ Donation Cell',
    hospitalId: 'hosp-02',
    address: 'Trichy Road, Coimbatore',
    district: 'Coimbatore',
    phone: '0422-2301393',
    coordinatorName: 'Dr. V. Premila (Regional Transplant Officer)',
    coordinatorPhone: '+91 98421 66320',
    accreditationNumber: 'TRANSTAN-TN-CBE-02',
    lat: 11.0016,
    lng: 76.9665,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'tc-03',
    name: 'PSG Hospitals Heart & Lung Institute',
    hospitalId: 'hosp-11',
    address: 'Avinashi Road, Peelamedu, Coimbatore',
    district: 'Coimbatore',
    phone: '0422-2570170',
    coordinatorName: 'Dr. J. Ramasamy',
    coordinatorPhone: '+91 98422 99101',
    accreditationNumber: 'NOTTO-CBE-PSG-08',
    lat: 11.0280,
    lng: 77.0040,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'tc-04',
    name: 'Christian Medical College (CMC) Renal & Liver Transplant Unit',
    hospitalId: 'hosp-12',
    address: 'Ida Scudder Road, Vellore',
    district: 'Vellore',
    phone: '0416-2281000',
    coordinatorName: 'Dr. George Thomas (Chief Coordinator)',
    coordinatorPhone: '+91 98410 44320',
    accreditationNumber: 'NOTTO-VEL-CMC-01',
    lat: 12.9246,
    lng: 79.1350,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'tc-05',
    name: 'RGGGH Institute of Nephrology & Organ Allocation Center',
    hospitalId: 'hosp-14',
    address: 'EVR Periyar Salai, Chennai',
    district: 'Chennai',
    phone: '044-25305000',
    coordinatorName: 'Dr. P. Ravichandran (Apex State Director)',
    coordinatorPhone: '+91 98400 11990',
    accreditationNumber: 'TRANSTAN-APEX-CHN-01',
    lat: 13.0805,
    lng: 80.2785,
    updatedAt: new Date().toISOString()
  }
];

export const seedIoTDevices = [
  {
    id: 'iot-01',
    deviceCode: 'REVIVE-BED-TN01',
    deviceType: 'BED_OCCUPANCY',
    deviceLabel: 'Smart Load Cell Bed Sensor ICU-03',
    facilityType: 'HOSPITAL',
    facilityId: 'hosp-01',
    facilityName: 'GH Erode',
    locationLabel: 'ICU Ward Bed #03',
    status: 'ONLINE',
    batteryLevel: 94,
    signalStrength: -62,
    lastSeen: new Date(Date.now() - 15 * 1000).toISOString(),
    telemetry: {
      occupancy: true,
      pressure: 72.4, // kg weight detected
      heartRate: 78,
      spO2: 98
    },
    updatedAt: new Date().toISOString()
  },
  {
    id: 'iot-02',
    deviceCode: 'REVIVE-COLD-PH04',
    deviceType: 'COLD_STORAGE',
    deviceLabel: 'ESP32 Vaccine & Insulin Freezer Monitor',
    facilityType: 'PHARMACY',
    facilityId: 'ph-01',
    facilityName: 'Sri Lakshmi Medicals, Erode',
    locationLabel: 'Cold Storage Room Unit A',
    status: 'ONLINE',
    batteryLevel: 98,
    signalStrength: -58,
    lastSeen: new Date(Date.now() - 28 * 1000).toISOString(),
    telemetry: {
      temperature: 3.8, // Â°C (safe range 2-8Â°C)
      humidity: 52 // %
    },
    updatedAt: new Date().toISOString()
  },
  {
    id: 'iot-03',
    deviceCode: 'REVIVE-OXY-ICU02',
    deviceType: 'OXYGEN_PRESSURE',
    deviceLabel: 'Liquid Medical Oxygen Line Pressure Transducer',
    facilityType: 'HOSPITAL',
    facilityId: 'hosp-02',
    facilityName: 'CMCH Coimbatore',
    locationLabel: 'Trauma ICU Central Gas Manifold',
    status: 'ONLINE',
    batteryLevel: 100,
    signalStrength: -50,
    lastSeen: new Date(Date.now() - 8 * 1000).toISOString(),
    telemetry: {
      pressure: 4.2, // Bar (Standard line pressure)
      flowRate: 35.8 // L/min total manifold draw
    },
    updatedAt: new Date().toISOString()
  },
  {
    id: 'iot-04',
    deviceCode: 'REVIVE-AMB-TN108',
    deviceType: 'AMBULANCE_TRACKER',
    deviceLabel: 'Rural GPS & Tele-ECG Gateway (TN-33-G-1108)',
    facilityType: 'AMBULANCE',
    facilityId: 'hosp-01',
    facilityName: '108 Ambulance Unit Erode South',
    locationLabel: 'Active Transit: Modakkurichi towards GH Erode',
    status: 'ONLINE',
    batteryLevel: 88,
    signalStrength: -68,
    lastSeen: new Date(Date.now() - 5 * 1000).toISOString(),
    telemetry: {
      gpsLat: 11.2850,
      gpsLng: 77.7520,
      heartRate: 84,
      spO2: 96
    },
    updatedAt: new Date().toISOString()
  },
  {
    id: 'iot-05',
    deviceCode: 'REVIVE-VITALS-RUR08',
    deviceType: 'VITAL_MONITOR',
    deviceLabel: 'Rural Tele-Clinic Pulse & SpO2 Kiosk',
    facilityType: 'RURAL_CLINIC',
    facilityId: 'hosp-16',
    facilityName: 'PHC Modakkurichi',
    locationLabel: 'Triage Room Station 1',
    status: 'ONLINE',
    batteryLevel: 91,
    signalStrength: -72,
    lastSeen: new Date(Date.now() - 40 * 1000).toISOString(),
    telemetry: {
      heartRate: 72,
      spO2: 99,
      temperature: 36.6
    },
    updatedAt: new Date().toISOString()
  }
];

export const seedUsers = [
  {
    id: 'usr-01',
    name: 'Ramesh Shanmugam',
    email: 'user@revive.demo',
    phone: '+91 98421 55678',
    passwordHash: 'demo123', // Demo verification
    role: 'USER',
    mode: 'BASIC',
    language: 'en',
    district: 'Coimbatore',
    lat: 11.0168,
    lng: 76.9558
  },
  {
    id: 'usr-02',
    name: 'Sri Lakshmi Medicals Staff',
    email: 'pharmacy@revive.demo',
    phone: '+91 94432 11029',
    passwordHash: 'demo123',
    role: 'PHARMACY',
    mode: 'BASIC',
    language: 'en',
    district: 'Erode',
    pharmacyId: 'ph-01',
    lat: 11.3410,
    lng: 77.7172
  },
  {
    id: 'usr-03',
    name: 'Dr. K. Swaminathan (Health Mission Director)',
    email: 'admin@revive.demo',
    phone: '+91 94430 00108',
    passwordHash: 'demo123',
    role: 'ADMIN',
    mode: 'ADVANCED',
    language: 'en',
    district: 'Chennai',
    lat: 13.0827,
    lng: 80.2707
  }
];
